//! Embeds the built UI (`src-tauri/dist`, the Vite output used by both the
//! Tauri shell and this runtime) into the binary via a generated asset
//! table. If the UI has not been built yet, a fallback page is embedded so
//! `cargo build`/`cargo test` always succeed; the runtime shows honest
//! instructions instead of pretending the UI exists.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=../../src-tauri/dist");
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let dist = manifest_dir.join("../../src-tauri/dist");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut entries);
        entries.sort();
    }

    let mut src = String::from("// Generated by crates/server/build.rs — embedded UI assets.\n");
    src.push_str("pub static ASSETS: &[(&str, &[u8])] = &[\n");
    for (rel, path) in &entries {
        let abs = path.to_string_lossy().replace('\\', "/");
        src.push_str(&format!(
            "    (\"{}\", include_bytes!(\"{}\")),\n",
            rel.replace('"', "\\\""),
            abs.replace('"', "\\\"")
        ));
    }
    src.push_str("];\n");
    fs::write(out_dir.join("ui_assets.rs"), src).expect("write ui_assets.rs");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect(root, &p, out);
        } else if let Ok(rel) = p.strip_prefix(root) {
            let rel = rel.to_string_lossy().replace('\\', "/");
            // Vite emits hashed asset filenames; keep them verbatim.
            out.push((rel, p));
        }
    }
}
